---

galaxy_path: "{{ playbook_dir }}/roles.galaxy"
# Compare git versions for breaking changes or new variables. example:
# https://github.com/n0emis/ansible-role-bigbluebutton/compare/21b0b62579777056d2fbc1b8c5826d5793868a95...master
# Git commit or release version of bbb_role_git
bbb_role_ver: 21b0b62579777056d2fbc1b8c5826d5793868a95
# https://github.com/n0emis/ansible-role-bigbluebutton
bbb_galaxy_role: n0emis.bigbluebutton

# https://github.com/geerlingguy/ansible-role-nodejs/releases
nodejs_galaxy_role: geerlingguy.nodejs
nodejs_role_ver: 5.1.1
# User for whom the npm packages will be installed, defaults to ansible_user.
nodejs_install_npm_user: npmuser
# https://github.com/geerlingguy/ansible-role-docker/releases
docker_galaxy_role: geerlingguy.docker
docker_role_ver: 3.1.0
# https://github.com/geerlingguy/ansible-role-pip/releases
pip_galaxy_role: geerlingguy.pip
pip_role_ver: 2.0.0
