---

galaxy_path: "{{ playbook_dir }}/roles.galaxy"
# Git commit or release version of bbb_role_git
bbb_role_ver: 0104e9eefcaf88b9129a287953984fcaa63adc41
# https://github.com/n0emis/ansible-role-bigbluebutton
bbb_galaxy_role: n0emis.bigbluebutton

# https://github.com/geerlingguy/ansible-role-nodejs/releases
nodejs_galaxy_role: geerlingguy.nodejs
nodejs_role_ver: 5.1.1
# User for whom the npm packages will be installed, defaults to ansible_user.
nodejs_install_npm_user: npmuser
# https://github.com/geerlingguy/ansible-role-docker/releases
docker_galaxy_role: geerlingguy.docker
docker_role_ver: 3.1.0
# https://github.com/geerlingguy/ansible-role-pip/releases
pip_galaxy_role: geerlingguy.pip
pip_role_ver: 2.0.0

# Python packages Ubuntu PPA repository
python_repo: 'ppa:deadsnakes/ppa'
# Python version to install
python_version: 3.7
