---

galaxy_path: "{{ playbook_dir }}/roles.galaxy"
# Git commit or release version of bbb_role_git
# https://github.com/ebbba-org/ansible-role-bigbluebutton/releases
bbb_role_ver: v2.3.1-a1.1.0
bbb_galaxy_role: ebbba.bigbluebutton
# Defeault presentation PDF file located in the files role directory
bbb_default_pdf: default.pdf

# https://github.com/geerlingguy/ansible-role-nodejs/releases
nodejs_galaxy_role: geerlingguy.nodejs
nodejs_role_ver: 5.1.1
# User for whom the npm packages will be installed, defaults to ansible_user.
nodejs_install_npm_user: npmuser
# https://github.com/geerlingguy/ansible-role-docker/releases
docker_galaxy_role: geerlingguy.docker
docker_role_ver: 3.1.2
# https://github.com/geerlingguy/ansible-role-pip/releases
pip_galaxy_role: geerlingguy.pip
pip_role_ver: 2.0.0
pip_install_packages:
  # https://pypi.org/project/docker/#history
  - name: docker
    version: "5.0.0"

# Generate BBB secrets if not defined in the inventory
bbb_coturn_secret: "{{ lookup('password', '/tmp/pass length=90) }}"
bbb_turn_secret: "{{ lookup('password', '/tmp/pass length=90) }}"
bbb_greenlight_secret: "{{ lookup('password', '/tmp/pass length=90) }}"
bbb_greenlight_db_password: "{{ lookup('password', '/tmp/pass length=90) }}"
bbb_freeswitch_socket_password: "{{ lookup('password', '/tmp/pass length=90) }}"
