---

galaxy_path: "{{ playbook_dir }}/roles.galaxy"
# https://github.com/ebbba-org/ansible-role-bigbluebutton/releases
bbb_role_ver: b2fd7bdef8975d278dbab0bc3a1097e748de9ff3
bbb_galaxy_role: ebbba.bigbluebutton
bbb_git_role: https://github.com/ebbba-org/ansible-role-bigbluebutton
# Default presentation PDF file located in the files role directory
bbb_default_pdf: default.pdf

# https://github.com/geerlingguy/ansible-role-nodejs/releases
nodejs_galaxy_role: geerlingguy.nodejs
nodejs_role_ver: 5.1.1
# User for whom the npm packages will be installed, defaults to ansible_user.
nodejs_install_npm_user: npmuser
# https://github.com/geerlingguy/ansible-role-docker/releases
docker_galaxy_role: geerlingguy.docker
docker_role_ver: 3.1.2

# Generate BBB secrets if not defined in the inventory
bbb_coturn_secret: "{{ lookup('password', '/tmp/pw length=90') }}"
bbb_turn_secret: "{{ lookup('password', '/tmp/pw length=90') }}"
bbb_greenlight_secret: "{{ lookup('password', '/tmp/pw length=90') }}"
bbb_greenlight_db_password: "{{ lookup('password', '/tmp/pw length=90') }}"
bbb_freeswitch_socket_password: "{{ lookup('password', '/tmp/pw length=90') }}"
