---

- name: Ensures backup directory {{ mc_backup_dir }} exists
  file:
    state: directory
    path: "{{ mc_backup_dir }}"

- name: Sets cron to log standard messages, plus jobs with non 0 exit status
  lineinfile:
    path: /etc/default/cron
    regexp: "^ # EXTRA_OPTS='-L 5'"
    line: "EXTRA_OPTS='-L 5'"
  notify: restart cron

- name: Creates a daily backup cronjob to backup all mailcow data at 4:30 AM
  cron:
    minute: "30"
    hour: "4"
    name: Backup all mailcow data
    cron_file: "{{ mc_cron_bak }}"
    user: root
    job: >-
      BACKUP_LOCATION={{ mc_backup_dir }}
      {{ mc_scripts_dir }}/backup_and_restore.sh backup all"

- name: Creates a daily cronjob to remove backup directories older than 7 days
  cron:
    minute: "30"
    hour: "12"
    name: Remove old backup directories
    cron_file: "{{ mc_cron_bak_clean }}"
    user: root
    job: >-
      find {{ mc_backup_dir }} -name 'mailcow-*'
        -mtime +7 -type d -exec rm -rf '{}' \\;

- name: List Mailcow cron entries
  debug: var={{ lookup('file', item) }}
  with_items:
    - "/etc/cron.d/{{ mc_cron_bak }}"
    - "/etc/cron.d/{{ mc_cron_bak_clean }}"
