---

- name: Ensures backup directory {{ mc_backup_dir }} exists
  file:
    state: directory
    path: "{{ mc_backup_dir }}"

- name: Sets cron to log standard messages, plus jobs with non 0 exit status
  lineinfile:
    path: /etc/default/cron
    regexp: "^ # EXTRA_OPTS='-L 5'"
    line: "EXTRA_OPTS='-L 5'"
  notify: restart cron

# https://mailcow.github.io/mailcow-dockerized-docs/b_n_r_backup/
- name: Creates a daily backup cronjob to backup all mailcow data at 4:30 AM
  cron:
    minute: "30"
    hour: "4"
    name: "Backup mailcow, delete backups older than {{ mc_bak_rm }} days"
    cron_file: "{{ mc_cron_bak }}"
    user: "{{ mc_cron_user }}"
    job: >
      {{ mc_scripts_dir }}/backup_and_restore.sh backup all
      --delete-days {{ mc_bak_rm }}

- name: Creates crontab's environment variable {{ mc_cron_env }}
  cron:
    name: "{{ mc_cron_env }}"
    env: true
    cron_file: "{{ mc_cron_bak }}"
    user: "{{ mc_cron_user }}"
    job: "{{ mc_backup_dir }}"

- name: Creates a daily cronjob to remove backup directories older than 7 days
  cron:
    minute: "30"
    hour: "12"
    name: Remove old backup directories
    cron_file: "{{ mc_cron_bak_clean }}"
    user: root
    job: >-
      find {{ mc_backup_dir }} -name 'mailcow-*'
        -mtime +7 -type d -exec rm -rf '{}' \\;

- name: Print Mailcow cronjob
  debug: var={{ lookup('file', item)|quote}}
  with_items:
    - "{{ mc_cron_bak }}"
