---

- name: Installs DNS check dependencies
  package:
    name: dnsutils
    state: present

- name: Query IP address of {{ mc_fqdn }}
  command: dig @{{ dig_server }} {{ mc_fqdn }} +short
  register: hostname_dig_ip

- debug:
    msg: >-
      The results of `dig @{{ dig_server }} {{ mc_fqdn }} +short`:
        {{ hostname_dig_ip.stdout }}

- name: Fails if {{ mc_fqdn }} doesn't resolve to {{ mc_ip }}
  fail:
    msg: "The hostname, {{ mc_fqdn }} must resolve to: {{ mc_ip }}"
  when: hostname_dig_ip.stdout != mc_ip

- name: Checks the MX record of {{ mc_domain }}
  command: dig @{{ dig_server }} MX {{ mc_domain }} +short
  register: mx_hostname_dig_ip

- debug:
    msg: >-
      The results of `dig @{{ dig_server }} MX {{ mc_domain }} +short`:
        {{ mx_hostname_dig_ip.stdout }}

- name: Fails if {{ mc_domain }} MX record is not {{ mc_fqdn }}
  fail:
    msg: >-
      The MX record of {{ mc_domain }} should have the following DNS entry:
        10 {{ mc_fqdn }}.
  when: mx_hostname_dig_ip.stdout != '10 {{ mc_fqdn }}.'

- name: Checks the IP address of {{ mc_autod }}
  command: dig @{{ dig_server }} {{ mc_autod }} +short
  register: autodiscover_hostname_dig_ip

- debug:
    msg: >-
      The results of `dig @{{ dig_server }} {{ mc_autod }} +short`:
        {{ autodiscover_hostname_dig_ip.stdout }}

- name: Fails if {{ mc_autod }} doesn't resolve to {{ mc_ip }}
  fail:
    msg: "The hostname, {{ mc_autod }} must resolve to: {{ mc_ip }}"
  when: autodiscover_hostname_dig_ip.stdout != mc_ip

- name: Checks the IP address of autoconfig.{{ mc_fqdn }}
  command: dig @{{ dig_server }} autoconfig.{{ mc_fqdn }} +short
  register: autoconfig_hostname_dig_ip

- debug:
    msg: >-
      The results of `dig @{{ dig_server }} autoconfig.{{ mc_fqdn }} +short`:
        {{ autoconfig_hostname_dig_ip.stdout }}
