---

- name: Clones mailcow repo
  git:
    repo: "{{ mc_git_repo }}"
    version: "{{ mc_git_version }}"
    dest: "{{ mc_install_dir }}"
    clone: true
    update: true
    force: true

- name: Templates mailcow config
  template:
    src: mailcow.conf.j2
    dest: "{{ mc_install_dir }}/mailcow.conf"

- name: Pulls docker images & start containers
  docker_compose:
    project_src: "{{ mc_install_dir }}"
    pull: true
