---

# https://mailcow.github.io/mailcow-dockerized-docs/prerequisite-system/#firewall-ports
- name: Check if any of mailcow's standard ports are in use
  ansible.builtin.debug:
    msg: TCP port {{ item.port }} by pid {{ item.pid }} violates the whitelist
  vars:
    tcp_listen_violations: "{{ ansible_facts.tcp_listen | selectattr('port', 'in', tcp_whitelist) | list }}"
    tcp_whitelist:
      - 110
      - 25
      - 4190
      - 443
      - 465
      - 587
      - 80
      - 993
      - 995
  loop: "{{ tcp_listen_violations }}"

- name: Checks if mailcow config exists
  stat:
    path: "{{ mc_install_dir }}/mailcow.conf"
  register: mc_conf
  tags: update

- name: Sets hostname
  hostname:
    name: "{{ mc_hostname }}"
  notify:
    - restart systemd-logind
  when: not mc_conf.stat.exists

- name: Templates hosts file with FQDN and hostname
  template:
    src: hosts.j2
    dest: /etc/hosts
  notify:
    - restart systemd-logind
  when: not mc_conf.stat.exists

- name: Sets timezone
  timezone:
    name: "{{ mc_timezone }}"
  when: not mc_conf.stat.exists

- name: Installs mailcow
  include_tasks: install-mailcow.yml
  when: not mc_conf.stat.exists

# Clamd uses lots of disk space when not enough memory
# https://github.com/mailcow/mailcow-dockerized/issues/1817
- name: Sets swap
  import_tasks: set-swap.yml
  when: mc_set_swap

- name: Sets mailcow backup
  import_tasks: backup-mailcow.yml
  when: mc_backup_dir != "none"
  tags: backup

- name: Displays post install message
  debug:
    msg: 'Visit https://{{ mc_fqdn }} and change default password `moohoo`!'
  when: not mc_conf.stat.exists

- name: Checks mailcow's DNS entries
  include_tasks: check-dns.yml
  when: mc_dns_check

- name: Updates mailcow
  import_tasks: update-mailcow.yml
  when: mc_check_updates and mc_conf.stat.exists
  tags: update
