---

# exit codes => 0: update available, 3: no updates
- name: run mailcow update script
  command: "./update.sh --check"
  args:
    chdir: "{{ mc_install_dir }}"
  register: check_updates
  failed_when: check_updates.rc == 1

- name: check if no updates are available
  debug:
    msg: 'No Mailcow updates available'
  when: check_updates.rc == 3

- name: prefetch new images
  command: "./update.sh --prefetch"
  args:
    chdir: "{{ mc_install_dir }}"
  when: check_updates.rc  == 0

- name: update mailcow
  command: "./update.sh --force"
  args:
    chdir: "{{ mc_install_dir }}"
  failed_when: check_updates.rc == 1
  register: update_script
  until: update_script.rc != 2
  notify:
    - docker-compose up

- name: Send update messages to syslog
  syslogger:
    msg: "Mailcow update: {{ update_script.stdout }}"
    facility: "daemon"
    log_pid: true
