---

dist: bionic
language: python
python: "3.9"

jobs:
  include:
#  - name: "Testing ansible playbook `deploy-mailserver.yml`"
#    env: TEST_ROLE=mailcow
#  - name: "Testing ansible playbook `deploy-update.yml`"
#    env: TEST_ROLE=update
#  - name: "Testing ansible playbook `deploy-discourse.yml`"
#    env: TEST_ROLE=discourse
  - name: "Testing ansible playbook `deploy-bigbluebutton.yml`"
    env: TEST_ROLE=bigbluebutton
#  - name: "Testing ansible playbook `deploy-matterbridge.yml`"
#    env: TEST_ROLE=matterbridge

cache:
  directories:
    - /home/travis/.vagrant.d/boxes
    - /home/travis/.cache/pipenv

install:
  - cd ci && ./install.sh

script:
  - cd ${TRAVIS_BUILD_DIR}/ansible/roles/$TEST_ROLE
  - sudo -E pipenv run molecule lint
  - sudo -E pipenv run molecule syntax
  - travis_wait 30 sudo -E pipenv run molecule converge
  - travis_wait 30 sudo -E pipenv run molecule idempotence
