---

dist: bionic
language: python
python: "3.8"

jobs:
  include:
  - name: "Testing ansible playbook `deploy-discourse.yml`"
    env: TEST_ROLE=discourse
  - name: "Testing ansible playbook `deploy-bigbluebutton.yml`"
    env: TEST_ROLE=bigbluebutton

cache:
  directories:
    - /home/travis/.vagrant.d/boxes
    - /home/travis/.cache/pipenv

install:
  - cd ci && ./install.sh

script:
  - cd ${TRAVIS_BUILD_DIR}/ansible/roles/$TEST_ROLE
    # Workaround: file owner (travis) does not match current user (root)
    # (/home/travis/.netrc,", "line 3)
  - sudo chown -R root:root /home/travis/.netrc
  - sudo -E pipenv run molecule lint
  - sudo -E pipenv run molecule syntax
  - travis_wait 30 sudo -E pipenv run molecule converge
  - travis_wait 30 sudo -E pipenv run molecule idempotence
