---

- name: Install BigBlueButton dependencies via Ansible Galaxy
  become: false
  delegate_to: localhost
  command: |
      ansible-galaxy install --force --roles-path "{{ galaxy_path }}"
        "{{ item.name }}","{{ item.version }}"
  args:
    creates: "{{ galaxy_path }}/{{ item.name }}"
  with_items:
    - { name: "{{ bbb_galaxy_role }}", version: "{{ bbb_role_ver }}" }
    - { name: "{{ nodejs_galaxy_role }}", version: "{{ nodejs_role_ver }}" }
    - { name: "{{ docker_galaxy_role }}", version: "{{ docker_role_ver }}" }
    - { name: "{{ pip_galaxy_role }}", version: "{{ pip_role_ver }}" }

- name: Create NodeJS npm user
  user:
    name: "{{ nodejs_install_npm_user }}"
    create_home: false
    comment: NodeJS npm user

- name: Import BigBlueButton Ansible Galaxy role
  include_role:
    name: "{{ galaxy_path }}/{{ bbb_galaxy_role }}"
    public: true
  vars:
    playbook_dir: "{{ galaxy_path }}/{{ bbb_galaxy_role }}"

- name: Wait for 20 seconds for Greenlight DB to initialize
  wait_for:
    timeout: 20
  delegate_to: localhost

  # https://docs.bigbluebutton.org/greenlight/gl-admin.html#creating-an-administrator-account
- name: Create Greenlight admin user
  command: >
    docker exec greenlight-v2 bundle exec rake
    user:creare['{{ bbb_adm.name }}','{{ bbb_adm.email }}','{{ bbb_adm.pass }}','admin']
  # TODO: Make this task idempotent by checking if the user exists
  changed_when: "'molecule-idempotence-notest' not in ansible_skip_tags"
