---

- name: Add repository {{ python_repo }}
  apt_repository:
    repo: '{{ python_repo }}'

- name: Install Python version {{ python_version }}
  apt:
    name: 'python{{ python_version }}'

- name: Install BigBlueButton dependencies via Ansible Galaxy
  become: false
  delegate_to: localhost
  command: |
      ansible-galaxy install --force --roles-path "{{ galaxy_path }}"
        "{{ item.name }}","{{ item.version }}"
  args:
    creates: "{{ galaxy_path }}/{{ item.name }}"
  with_items:
    # yamllint disable rule:braces
    - { name: "{{ bbb_galaxy_role }}", version: "{{ bbb_role_ver }}" }
    - { name: "{{ nodejs_galaxy_role }}", version: "{{ nodejs_role_ver }}" }
    - { name: "{{ docker_galaxy_role }}", version: "{{ docker_role_ver }}" }
    - { name: "{{ pip_galaxy_role }}", version: "{{ pip_role_ver }}" }
    # yamllint disable rule:braces

- name: Create NodeJS npm user
  user:
    name: "{{ nodejs_install_npm_user }}"
    create_home: false
    comment: NodeJS npm user

- name: Import BigBlueButton Ansible Galaxy role
  include_role:
    name: "{{ galaxy_path }}/{{ bbb_galaxy_role }}"
    public: true
  vars:
    playbook_dir: "{{ galaxy_path }}/{{ bbb_galaxy_role }}"

- name: Wait for 20 seconds for Greenlight DB to initialize
  wait_for:
    timeout: 20
  delegate_to: localhost
