---

- name: Install BigBlueButton dependencies via Ansible Galaxy
  become: false
  delegate_to: localhost
  command: |
      ansible-galaxy install --force --roles-path "{{ galaxy_path }}"
        "{{ item.name }}","{{ item.version }}"
  args:
    creates: "{{ galaxy_path }}/{{ item.name }}"
  with_items:
    # yamllint disable rule:braces
    - { name: "{{ bbb_galaxy_role }}", version: "{{ bbb_role_ver }}" }
    - { name: "{{ nodejs_galaxy_role }}", version: "{{ nodejs_role_ver }}" }
    - { name: "{{ docker_galaxy_role }}", version: "{{ docker_role_ver }}" }
    - { name: "{{ pip_galaxy_role }}", version: "{{ pip_role_ver }}" }
    # yamllint disable rule:braces

- name: Create NodeJS npm user
  user:
    name: "{{ nodejs_install_npm_user }}"
    create_home: false
    comment: NodeJS npm user

- name: Log into DockerHub (avoid rate limits)
  docker_login:
    username: "{{ dhub_usr }}"
    password: "{{ dhub_pwd }}"
  when:
    - dhub_usr is defined
    - dhub_pwd is defined

- name: Import BigBlueButton Ansible Galaxy role
  include_role:
    name: "{{ galaxy_path }}/{{ bbb_galaxy_role }}"
    public: true
  vars:
    playbook_dir: "{{ galaxy_path }}/{{ bbb_galaxy_role }}"

- name: Wait for 20 seconds for Greenlight DB to initialize
  wait_for:
    timeout: 20
  delegate_to: localhost

- name: Upload default BigBlueButton presentation
  copy:
    mode: 0644
    src: "{{ bbb_default_pdf }}"
    dest: "{{ bbb_nginx_root }}/default.pdf"
  when: bbb_default_pdf is exists

- name: Run bbb-conf --check
  command: bbb-conf --check
  register: bbb_conf_check_out

- debug:
    msg: "{{ bbb_conf_check_out }}"
