---

- name: Install BigBlueButton dependencies via Ansible Galaxy
  become: no
  local_action: |
    command ansible-galaxy install --force --roles-path {{ galaxy_path }}
        git+{{ bbb_role_git }},{{ bbb_role_ver }}
        {{ nodejs_galaxy_role }},{{ nodejs_role_ver }}
        {{ docker_galaxy_role }},{{ docker_role_ver }}
        {{ pip_galaxy_role }},{{ pip_role_ver }}

- name: Create NodeJS npm user
  user:
    name: "{{ nodejs_install_npm_user }}"
    create_home: false
    comment: NodeJS npm user

- name: Import BigBlueButton Ansible Galaxy role
  include_role:
    name: "{{ galaxy_path }}/{{ bbb_role }}"
    public: yes
  vars:
    playbook_dir: "{{ galaxy_path }}/{{ bbb_role }}"

- name: Wait for 60 seconds - Greenlight DB init
  wait_for:
    timeout: 60
  delegate_to: localhost

  # https://docs.bigbluebutton.org/greenlight/gl-admin.html#creating-an-administrator-account
- name: Create Greenlight admin user
  command: >
    docker exec greenlight-v2 bundle exec rake
    user:create['{{ bbb_adm.name }}','{{ bbb_adm.email }}','{{ bbb_adm.pass }}','admin']
