---

driver:
  name: vagrant
  provider:
    name: libvirt

lint: |
  set -e
  yamllint .

platforms:
  - name: ubuntu1804-instance
    box: generic/ubuntu1804
  - name: debian9-instance
    box: generic/debian9
  - name: debian10-instance
    box: generic/debian10

provisioner:
  name: ansible
  options:
    verbose: true
  lint:
    name: ansible-lint
  inventory:
    links:
      group_vars: ../../../../inventory/molecule/group_vars/
      host_vars: ../../../../inventory/molecule/host_vars/
  playbooks:
    prepare: prepare.yml
    converge: ../../../../deploy-update.yml

verifier:
  name: testinfra
  directory: tests
  options:
    verbose: true
  lint:
    name: flake8
