bbb_letsencrypt_enable: false
bbb_letsencrypt_email: mail@example.com
# Use latest to update BBB and present to keep currently installed version.
bbb_state: "latest"
bbb_api_demos_enable: false
bbb_disable_recordings: true
# Greenlight registration mode: open (default), invite, approval
bbb_greenlight_default_registration: approval
# https://docs.bigbluebutton.org/2.2/troubleshooting.html#freeswitch-fails-to-start-with-a-setscheduler-error
bbb_cpuschedule: false
# https://docs.bigbluebutton.org/2.2/troubleshooting.html#freeswitch-fails-to-bind-to-port-8021
bbb_freeswitch_ipv6: false
# Generate Diff-Hellmann for nginx
bbb_nginx_dh: yes
bbb_app_log_level: 'ERROR'
bbb_apt_mirror: https://packages-eu.bigbluebutton.org

# https://github.com/bigbluebutton/bigbluebutton/blob/develop/bigbluebutton-html5/private/config/settings.yml
bbb_meteor:
  public:
    app:
      clientTitle: "Molecule - BigBlueButton"
      helpLink: "https://privacylx.org/community/"
      mirrorOwnWebcam: true
    kurento:
      cameraProfiles:
      - id: low
        name: Low quality
        default: true
        bitrate: 50
      - id: medium
        name: Medium quality
        default: false
        bitrate: 100
      - id: high
        name: High quality
        default: false
        bitrate: 200
      - id: hd
        name: High definition
        default: false
        bitrate: 400
        hidden: true
      cameraQualityThresholds:
        enabled: true
        thresholds:
          - threshold: 8
            profile: low-u8
          - threshold: 12
            profile: low-u12
          - threshold: 15
            profile: low-u15
          - threshold: 20
            profile: low-u20
          - threshold: 25
            profile: low-u25
          - threshold: 30
            profile: low-u30

bbb_coturn_secret: "{{ lookup('password', '/tmp/passwordfile length=80') }}"
bbb_turn_secret: "{{ lookup('password', '/tmp/passwordfile length=80') }}"
bbb_greenlight_secret: "{{ lookup('password', '/tmp/passwordfile length=80') }}"
bbb_greenlight_db_password: "{{ lookup('password', '/tmp/passwordfile length=80') }}"
# BigBlueButton admin user
bbb_adm:
    name: Admin Test User
    email: admintestusr@example.org
    pass: "{{ lookup('password', '/tmp/passwordfile length=30 chars=ascii_letters') }}"

bbb_greenlight_users:
  - { name: '{{ bbb_adm.name }}', email: '{{ bbb_adm.email }}', password: '{{ bbb_adm.pass }}', type: 'admin' }
