---

driver:
  name: vagrant
  provider:
    name: libvirt

lint: |
  set -e
  yamllint .

platforms:
  - name: debian11-instance
    box: generic/debian11
    groups:
      - matterbridge

provisioner:
  name: ansible
  options:
    verbose: true
  lint:
    name: ansible-lint
  inventory:
    links:
      group_vars: ../../../../inventory/molecule/group_vars/
      host_vars: ../../../../inventory/molecule/host_vars/
  playbooks:
    prepare: prepare.yml
    converge: ../../../../deploy-matterbridge.yml

verifier:
  name: testinfra
  directory: tests
  options:
    verbose: true
  lint:
    name: flake8
