---

- name: restart systemd-logind
  service:
    name: systemd-logind
    state: restarted
  when: >
    ansible_service_mgr == 'systemd'

- name: restart cron
  service:
    name: cron
    state: restarted

- name: docker-compose up
  command: /usr/bin/docker-compose up --detach
  args:
    chdir: "{{ mc_install_dir }}"
