---

- name: Create {{ matterbridge_path }} dir
  file:
    path: "{{ matterbridge_path }}"
    state: directory

- name: Template matterbridge config from PATH: {{ matterbridge_template_path }}
  template:
    src: "{{ matterbridge_template_path }}//matterbridge.toml.j2"
    dest: "{{ matterbridge_path }}/matterbridge.toml"
  notify: restart matterbridge

- name: Deploy matterbridge
  docker_container:
    name: "{{ matterbridge_name }}"
    image: "{{ matterbridge_image }}"
    restart_policy: unless-stopped
    entrypoint: '/bin/matterbridge'
    volumes:
        - "{{ matterbridge_path }}/matterbridge.toml:/matterbridge.toml:ro"
  when: not matterbridge_debug

- name: Deploy matterbridge with debug log output
  docker_container:
    name: "{{ matterbridge_name }}"
    image: "{{ matterbridge_image }}"
    restart_policy: unless-stopped
    # Enable debug log output
    entrypoint: '/bin/matterbridge -debug'
    volumes:
        - "{{ matterbridge_path }}/matterbridge.toml:/matterbridge.toml:ro"
  when: matterbridge_debug
