---

- name: Creates Discourse directory {{ dis_path }}
  file:
    path: "{{ dis_path }}"
    state: directory

- name: Clones Discource git repository
  git:
    repo: "{{ dis_git }}"
    dest: "{{ dis_path }}"

- name: Templates Discourse container configuration
  template:
    src: standalone.yml.j2
    dest: "{{ dis_path }}/containers/app.yml"
  notify:
    launcher rebuild
