---

- name: Creates Discourse directory {{ dis_path }}
  file:
    path: "{{ dis_path }}"
    state: directory

- name: Creates safe git directory {{ dis_www_path }}
  community.general.git_config:
    name: safe.directory
    scope: system
    value: "{{ dis_www_path }}"

- name: (XXX test) show git confing
  command: git config --system --list
  register: gitconfig_output

- name: (XXX test) Show git config output
  debug:
    msg: "{{ gitconfig_output.stdout }}"

- name: (XXX test) add safe.directory config (with command module)
  command: git config --system --add safe.directory "{{ dis_www_path }}"

- name: Clones Discourse git repository
  git:
    repo: "{{ dis_git }}"
    dest: "{{ dis_path }}"

- name: Get Discourse container info
  docker_container_info:
    name: app
  register: discourse_container

- name: Templates Discourse container configuration
  template:
    src: standalone.yml.j2
    dest: "{{ dis_path }}/containers/app.yml"
  register: dis_template

- name: Print the status of the Discourse container
  debug:
    msg: "Container status: {{ discourse_container.container.State.Status }}"
  when:
    - discourse_container|bool
    - discourse_container.exists

- name: (Re)build Discourse container configuration
  command: "{{ dis_path }}/launcher rebuild app"
  when: not discourse_container.exists or dis_template.changed
  no_log: false

- name: Start Discourse container if it's already exist but not running
  command: "{{ dis_path }}/launcher start app"
  when:
    - not dis_template.changed
    - discourse_container.exists
    - discourse_container.container.State.Status != 'running'
