---

driver:
  name: vagrant
  provider:
    name: libvirt

lint: |
  set -e
  yamllint .

platforms:
  - name: debian9-instance
    box: generic/debian9
    memory: 2000
    cpus: 1
    groups:
      - mailserver
    command: |
      echo 'DOCKER_OPTS="$DOCKER_OPTS --registry-mirror=https://mirror.gcr.io"'
      sudo service docker restart
      docker system info
  - name: debian10-instance
    box: generic/debian10
    memory: 2000
    cpus: 1
    groups:
      - mailserver
    command: |
      echo 'DOCKER_OPTS="$DOCKER_OPTS --registry-mirror=https://mirror.gcr.io"'
      sudo service docker restart
      docker system info

provisioner:
  name: ansible
  options:
    verbose: true
  lint:
    name: ansible-lint
  inventory:
    links:
      group_vars: ../../../../inventory/molecule/group_vars/
  playbooks:
    prepare: prepare.yml
    converge: ../../../../deploy-mailserver.yml

verifier:
  name: testinfra
  directory: tests
  options:
    verbose: true
  lint:
    name: flake8
