---

- name: Prepare
  hosts: all
  become: true
  tasks:
    # Satisfy CI Molecule error
    # Docker SDK for Python: docker (Python >= 2.7) or docker-py (Python 2.6)
    - name: Install python package dependencies
      apt:
        pkg:
          - libffi-dev
          - python3-pip
    - name: Install docker-compose (pip)
      pip:
        executable: pip3
        name: docker-compose
