---

- name: Prepare
  hosts: all
  become: true
  tasks:
    # Satisfy CI Molecule error
    # Docker SDK for Python: docker (Python >= 2.7) or docker-py (Python 2.6)
    - name: Install python-package
      apt:
        name: python3-pip

    - name: Install python-package
      pip:
        name: docker-compose
