# Admin email address
admin_email: admin@example.org

# Lets Encrypt email
le_email: "{{ admin_email }}"
le_staging: true

# Discourse configuration
dis_plugins:
  - https://github.com/discourse/discourse-bbb.git

# DockerHub credentials set in Travis CI
dhub_usr: "{{ lookup('env', 'DOCKERHUB_USER') }}"
dhub_pwd: "{{ lookup('env', 'DOCKERHUB_PWD') }}"

# Ansible galaxy roles path
galaxy_path: "{{ playbook_dir }}/roles.galaxy"
