---

- name: Disk size
  hosts: all
  become: true
  tasks:
    - name: Disk usage from command module
      command: df -h
      register: df
    - name: Print df
      debug:
        var: df.stdout_lines
