---

driver:
  name: docker

lint: |
  set -e
  yamllint .

platforms:
  - name: instance
    image: ${MOLECULE_DISTRO:-ubuntu:18.04}
    groups:
      - bigbluebutton

provisioner:
  name: ansible
  options:
    verbose: true
  lint:
    name: ansible-lint
  inventory:
    links:
      group_vars: ../../../../inventory/molecule/group_vars/
  playbooks:
    prepare: prepare:yml
    converge: ../../../../deploy-bigbluebutton.yml

verifier:
  name: testinfra
  directory: tests
  options:
    verbose: true
  lint:
    name: flake8
