---

driver:
  name: vagrant
  provider:
    name: libvirt

lint: |
  set -e
  yamllint .

platforms:
  - name: ubuntu1804-instance
    box: generic/ubuntu1804
    memory: 4000
    cpus: 2
    groups:
      - bigbluebutton

provisioner:
  name: ansible
  options:
    verbose: true
  lint:
    name: ansible-lint
  inventory:
    links:
      group_vars: ../../../../inventory/molecule/group_vars/
  playbooks:
    converge: ../../../../deploy-bigbluebutton.yml

verifier:
  name: testinfra
  directory: tests
  options:
    verbose: true
  lint:
    name: flake8
