---

- name: Prepare
  hosts: all
  become: True
  tasks:
    - name: Install PyOpenSSL build requirements
      apt:
        update_cache: yes
        pkg:
          - libffi-dev
          - python3-pip
          - python3-setuptools

    - name: pip self-update
      command: pip3 install --upgrade pip
