---

- name: Prepare
  hosts: all
  become: True
  tasks:
    - name: Install python 3 package
      package:
        name: python3
        state: latest

    # Bug: https://github.com/pypa/get-pip/issues/83
    - name: Install pip3.5 workaround
      shell: |
        curl https://bootstrap.pypa.io/3.5/get-pip.py -o ./get-pip.py --fail \
          --silent --show-error && python ./get-pip.py && rm ./get-pip.py
