- name: Prepare
  hosts: all
  become: true
  tasks:
    - name: Add universe repository for bionic
      apt_repository:
        repo: deb http://archive.ubuntu.com/ubuntu bionic universe
        state: present
      when: ansible_distribution_release == 'bionic'
    - name: Install locales package
      apt:
        pkg: [ 'locales', 'dbus' ]
