---

- name: Prepare
  hosts: all
  become: True
  tasks:
    - name: Install PyOpenSSL build requirements
      apt:
        pkg:
          - python3-pip
          - python3-setuptools
        update_cache: yes
    - name: pip self-update
      pip:
        executable: pip3
        name: pip
        state: latest
