---

# See: https://github.com/pypa/pip/issues/9526
- name: Prepare
  hosts: all
  become: True
  tasks:
    - name: Install PyOpenSSL build requirements
      apt:
        name: ['python3-pip', 'python3-setuptools']
        update_cache: yes
    - name: pip self-update
      pip:
        name: pip
        version: '19.3.1'
