---

- name: Prepare
  hosts: all
  become: true
  tasks:
    # See: https://github.com/pypa/pip/issues/9526
    - name: Install PyOpenSSL build requirements
      apt:
        name: ['python3-pip', 'python3-setuptools']
        update_cache: true
    - name: pip self-update
      pip:
        name: pip
        version: '19.3.1'
    # XXX Hack to resolve DNS resolution issues in CI
    - name: Add a hosts entry to fix issues with CI DNS resolution
      lineinfile:
        path: /etc/hosts
        line: 167.99.180.121 ubuntu.bigbluebutton.org
        create: yes
