---

- name: Prepare
  hosts: all
  tasks:
    - name: Generate an OpenSSH keypair with the default values (4096 bits, rsa)
      openssh_keypair:
        path: /tmp/id_ssh_rsa
      register: m_ssh_key
