---

- name: Prepare
  hosts: all
  become: True
  tasks:
    - name: Install PyOpenSSL build requirements
      apt:
        name: python3-pip
    - name: pip self-update
      pip:
        name: pip
        state: latest
