---

- hosts: localhost
  connection: local
  gather_facts: false
  tags: always
  pre_tasks:
    - name: Set minimun required Ansible version
      set_fact:
        ansible_version_min: 2.11.1
    - name: Ensure we have minimum Ansible version "{{ ansible_version_min }}"
      assert:
        that: ansible_version.full is version('{{ ansible_version_min }}', '>=')
        msg: |
          You are using Ansible version: {{ ansible_version.full }}
          The minimum required version of Ansible is: {{ ansible_version_min }}
      run_once: true
