---

- hosts: localhost
  connection: local
  gather_facts: false
  tags: always
  tasks:
    - name: Ensure we have minimum Ansible version "{{ ansible_version_min }}"
      assert:
        msg: "ansible_version: {{ ansible_version }}"
        that: "ansible_version.full is version_compare('{{ ansible_version_min }}', '>=')"
      when: "ansible_version.full is version_compare('2.7', '<')"
      run_once: true

    - name: Ensure we have minimum Ansible version "{{ ansible_version_min }}"
      assert:
        that: "ansible_version.full is version_compare('{{ ansible_version_min }}', '>=')"
        fail_msg: >-
                  "ansible_version: {{ ansible_version.full }}"
                  "You must install Ansible version >= {{ ansible_version_min }}"
        success_msg: "ansible_version: {{ ansible_version.full }}"
      when: "ansible_version.full is version_compare('2.7', '>=')"
      run_once: true
