---

- import_playbook: ansible-version.yml

- name: "Set up a mailcow server"
  hosts: "{{ target if target is defined else 'mailserver' }}"
  become: true

  roles:
    - docker
    - mailcow

  tasks:
    - name: Include mailcow update role
      include_role:
        name: mailcow
      tags: update
      when: MOLECULE_STATE_FILE is defined
