---

- import_playbook: ansible-version.yml

- name: "Set up the matterbridge"
  hosts: "{{ target if target is defined else 'matterbridge' }}"
  become: true

  roles:
    - docker
    - matterbridge
