---

- import_playbook: ansible-version.yml

- name: "Run update role"
  hosts: all
  become: true
  roles:
    - update

- name: "Update mailserver (mailcow)"
  hosts: mailserver
  become: true
  tasks:
    - name: Run mailcow's update-mailcow task
      include_role:
        name: mailcow
        tasks_from: update-mailcow
  # Ignore error on check mode
  ignore_errors: "{{ ansible_check_mode }}"
