---

- import_playbook: ansible-version.yml

- name: "Run update role"
  hosts: all
  become: true
  roles:
    - update

- name: "Update mailserver (mailcow)"
  hosts: mailserver
  become: true
  roles:
    - { role: mailcow, tags: update }
