---

- name: Safe upgrade of all packages
  apt:
    cache_valid_time: "{{ apt_cache_time }}"
    upgrade: safe

- name: Install unattended-upgrades
  apt:
    pkg: "unattended-upgrades"
    state: present
  when: not unattended_mail

- name: Remove ssmtp package
  apt:
    pkg: ssmtp
    state: absent
    purge: yes

- name: Install unattended-upgrades and mail dependencies
  apt:
    pkg: ["unattended-upgrades", "msmtp-mta"]
    state: present
  when: unattended_mail | bool

- name: Create msmtp (email) configuration
  template:
    src: "{{ msmtp_conf }}.j2"
    dest: "{{ msmtp_conf_path }}"
    owner: root
    group: root
    mode: 0644
  # TODO check msmtp hanging for user prompt?
  #notify: check msmtp config
  when: unattended_mail | bool

- name: Create unattended-upgrades configuration
  template:
    src: "{{ item }}.j2"
    dest: "/etc/apt/apt.conf.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - 52unattended-upgrades
    - 20auto-upgrades

- name: Check if a reboot is required after upgrade
  stat:
    path: /var/run/reboot-required
  register: reboot_required
  notify: reboot
  when: reboot_enabled|default(false)|bool == true
