---

- fail:
    msg: "This role is supports Debian and Ubuntu hosts"
  when:
    - ansible_distribution != 'Debian'
    - ansible_distribution != 'Ubuntu'

- name: Include Debian/Ubuntu distribution tasks
  include_tasks: debian.yml
  when:
    - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- debug:
    msg: Kernel "{{ ansible_kernel }}"

- shell: /usr/bin/uptime
  register: uptime

- debug:
    msg: "{{ uptime.stdout }}"
  tags: molecule-idempotence-notest
